### ISSUE TITLE
Translate Wikipedia terminology

### ISSUE THREAD

**Issue by keynmol** [idio/json-wikipedia#28]
We have those `lang-en.properties` files.

We need them for the following languages:

- German
- Italian
- Spanish
- Portugese

**Comment by dav009** [comment]
keywords:
https://es.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=magicwords&format=json
https://de.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=magicwords&format=json

but also namespaces:
https://es.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=namespaces&format=json
https://de.wikipedia.org/w/api.php?action=query&meta=siteinfo&siprop=namespaces&format=json

**Comment by Lugrin** [comment]
Where are these files? Do you mean `locale-de.properties` in `json-wikipedia/src/main/resources/lang/`?
