### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by learnudon** [idio/json-wikipedia#42]
i try to build the project with the following command :+1: mvn assembly:assembly

but i always get the following error: 
 Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]

Anybody else run into this problem and know how to solve them?
i am using maven version 3.5 by the way

**Comment by keynmol** [comment]
Hi,

I've tried to reproduce it but couldn't:

```
$ docker run -it --rm --name my-maven-project-1 -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.5-jdk-8 mvn assembly:assembly

# looooooots of downloads

[INFO] Building jar: /usr/src/mymaven/target/json-wikipedia-1.2.0-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31:47 min
[INFO] Finished at: 2017-07-09T16:28:27Z
[INFO] Final Memory: 40M/246M
[INFO] ------------------------------------------------------------------------
```

This is using Maven 3.5 and JDK 8, I ran this command in the root of the repository. 

Try running `mvn clean && mvn assembly:assembly` or try using my exact command to produce a jar.

**Comment by learnudon** [comment]
Hi thanks for the suggestion. i dont think i have docker install. 
I run `mvn clean && mvn assembly:assembly` as per your suggestion on my laptop which run on ubuntu and it build successfully but on my windows pc the same error still happen. they both have maven 3.5 and java 1.8. Weird. I'll run the jar and hopefully everythings working. Thanks again.
