### ISSUE TITLE
Investigate moving to scala json parser of wiki dump

### ISSUE THREAD

**Issue by stathischaritos** [idio/json-wikipedia#48]
We can use this as a starting point.
https://github.com/mindfulmachines/wiki-parser

**Comment by tgalery** [comment]
Working with @stathischaritos at removing some deps from idio/json-wikipedia made me realise that that repo and java are bullshit. It might be nice to start a new project that parses wikimedia markup in Scala from scratch. To do the heavy lifting, we could use libs like

- [atto](https://github.com/tpolecat/atto)
- [parboiled2](https://github.com/sirthias/parboiled2)
